"""Daily digest emailer — HTML email with top movers and vibe checks."""

import json
import smtplib
import subprocess
import sys
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any

from polypulse.config import load_config


def _run_polypulse(*args: str) -> dict | list:
    """Run a polypulse command with --json and return parsed output."""
    cmd = [sys.executable, "-m", "polypulse.cli", *args, "--json"]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"polypulse {' '.join(args)} failed: {result.stderr}")
    return json.loads(result.stdout)


def fetch_digest_data(
    top_movers_fn=None,
    vibe_fn=None,
    num_vibes: int = 3,
) -> dict[str, Any]:
    """Gather data for the digest email.

    Args:
        top_movers_fn: Optional callable returning trade suggestions dict.
        vibe_fn: Optional callable(slug) returning vibe dict.
        num_vibes: Number of top markets to run vibe checks on.

    Returns:
        {"date": str, "movers": [...], "vibes": [...]}
    """
    # Top movers
    if top_movers_fn:
        movers_data = top_movers_fn()
    else:
        movers_data = _run_polypulse("trade", "--auto")

    suggestions = movers_data.get("suggestions", [])

    # Vibe checks for top N
    vibes = []
    for s in suggestions[:num_vibes]:
        slug = s.get("slug", "")
        if not slug:
            continue
        try:
            if vibe_fn:
                vibe = vibe_fn(slug)
            else:
                vibe = _run_polypulse("vibe", slug)
            vibes.append(vibe)
        except Exception:
            vibes.append({"slug": slug, "sentiment": "error", "summary": "Could not fetch vibe."})

    return {
        "date": datetime.now().strftime("%Y-%m-%d"),
        "movers": suggestions,
        "vibes": vibes,
    }


def render_html(data: dict[str, Any]) -> str:
    """Render digest data as an HTML email body."""
    date = data["date"]
    movers = data.get("movers", [])
    vibes = data.get("vibes", [])

    movers_rows = ""
    for m in movers:
        signal = m.get("signal", "?")
        color = "#22c55e" if signal == "BUY" else "#eab308"
        price = m.get("price")
        price_str = f"{price:.3f}" if price is not None else "?"
        vol = m.get("volume_24h", 0)
        if vol >= 1_000_000:
            vol_str = f"${vol / 1_000_000:.1f}M"
        elif vol >= 1_000:
            vol_str = f"${vol / 1_000:.0f}K"
        else:
            vol_str = f"${vol:,.0f}"
        movers_rows += f"""
        <tr>
            <td style="padding:8px;border-bottom:1px solid #eee;">
                <span style="color:{color};font-weight:bold;">{signal}</span>
            </td>
            <td style="padding:8px;border-bottom:1px solid #eee;">{m.get('question', m.get('slug', '?'))}</td>
            <td style="padding:8px;border-bottom:1px solid #eee;text-align:right;">{price_str}</td>
            <td style="padding:8px;border-bottom:1px solid #eee;text-align:right;">{vol_str}</td>
        </tr>"""

    vibes_html = ""
    for v in vibes:
        sentiment = v.get("sentiment", "?")
        emoji = {"bullish": "🟢", "bearish": "🔴", "neutral": "🟡"}.get(sentiment, "❓")
        vibes_html += f"""
        <div style="margin-bottom:12px;padding:12px;background:#f8f9fa;border-radius:8px;">
            <strong>{emoji} {v.get('slug', '?')}</strong>
            <span style="color:#666;margin-left:8px;">{sentiment.upper()}</span>
            <p style="margin:6px 0 0 0;color:#333;">{v.get('summary', '')}</p>
        </div>"""

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:600px;margin:0 auto;padding:20px;color:#1a1a1a;">
    <h1 style="color:#7c3aed;margin-bottom:4px;">📊 PolyPulse Daily Digest</h1>
    <p style="color:#666;margin-top:0;">{date}</p>

    <h2 style="border-bottom:2px solid #7c3aed;padding-bottom:4px;">🔥 Top Movers</h2>
    <table style="width:100%;border-collapse:collapse;">
        <tr style="background:#f1f5f9;">
            <th style="padding:8px;text-align:left;">Signal</th>
            <th style="padding:8px;text-align:left;">Market</th>
            <th style="padding:8px;text-align:right;">Price</th>
            <th style="padding:8px;text-align:right;">24h Vol</th>
        </tr>
        {movers_rows}
    </table>

    <h2 style="border-bottom:2px solid #7c3aed;padding-bottom:4px;margin-top:24px;">🧠 Vibe Checks</h2>
    {vibes_html if vibes_html else '<p style="color:#999;">No vibe checks available.</p>'}

    <hr style="margin-top:24px;border:none;border-top:1px solid #e5e7eb;">
    <p style="color:#999;font-size:12px;">Generated by PolyPulse CLI — the smart terminal layer for Polymarket.</p>
</body>
</html>"""


def send_email(
    html: str,
    recipient: str,
    subject: str | None = None,
    smtp_host: str = "smtp.gmail.com",
    smtp_port: int = 587,
    smtp_user: str = "",
    smtp_password: str = "",
) -> None:
    """Send the digest email via SMTP."""
    if not smtp_user or not smtp_password:
        raise RuntimeError(
            "SMTP credentials not configured. Set smtp_user and smtp_password "
            "in config.json or POLYPULSE_SMTP_USER / POLYPULSE_SMTP_PASSWORD env vars."
        )

    subject = subject or f"PolyPulse Digest — {datetime.now().strftime('%Y-%m-%d')}"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = smtp_user
    msg["To"] = recipient
    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP(smtp_host, smtp_port) as server:
        server.starttls()
        server.login(smtp_user, smtp_password)
        server.sendmail(smtp_user, recipient, msg.as_string())
